version: '3.8'

services:
  web:
    build: .
    image: web
    container_name: web
    ports:
      - "5000:5000"
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --log-config config/logging.conf
    volumes:
      - ./config/:/app/config/
      - ./logs/:/app/logs/
    environment:
      - CONFIG_PATH=config/config.toml
    depends_on:
      - redis

  worker:
    build: .
    image: worker
    container_name: worker
    command: dramatiq app:actors.broker --log-file sys.stderr --log-file logs/dramatiq.log
    volumes:
      - ./config/:/app/config/
      - ./logs/:/app/logs/
    environment:
      - CONFIG_PATH=config/config.toml
    depends_on:
      - redis

  redis:
     image: redis:7.2-rc2-alpine
     container_name: redis
     restart: always
     ports:
       - "6379:6379"