[api]
version = '0.1.0'
title = 'demo'
description = 'todo'
docs_url = '/'


[dashboard]
url = "/dashboard"


[redis]
host = "redis"
port = 6379


[actors.masscan]
binary = "/usr/bin/masscan"
command = [
    { field = "binary" },
    { value = "{target}", field = "target" },
    { name = "-p", field = "port_range" },
    { name = "--rate", field = "rate" },
    { name = "--source-ip", field = "source_ip" },
    { name = "-oJ", value = "-" }
]

[actors.httpx]
binary = 'bin/httpx'
command = [
    { field = "binary" },
    { name = "-u", field = "target" },
    { name = "-p", field = "port_range" },
    { value = "-json" },
    { value = "-silent" }
]