[api]
version = '0.1.0'
title = 'demo'
description = 'todo'
docs_url = '/'


[dashboard]
url = "/dashboard"


[redis]
host = "redis"
port = 6379
db = 0


[actors.port_scan.masscan]
binary = "/usr/bin/masscan"
command = [
    { field = "binary" },
    { value = "{target}", field = "target" },
    { option = "-p", field = "ports" },
    { option = "--rate", field = "rate" },
    { option = "--source-ip", field = "source_ip" },
    { option = "-oJ", value = "-" },
    { option = "--show", value = "all"}
]


[actors.service_scan.httpx]
binary = 'bin/httpx'
command = [
    { field = "binary" },
    { option = "-u", field = "target" },
    { option = "-p", field = "ports" },
    { value = "-tech-detect" },
    { value = "-json" },
    { value = "-silent" }
]

chains_command = [
    { field = "binary" },
    { value = "-tech-detect" },
    { value = "-json" },
    { value = "-silent" }
]