[api]
version = '0.1.0'
title = 'demo'
description = 'todo'
docs_url = '/'


[dashboard]
url = "/dashboard"


[redis]
host = "redis"
port = 6379


[binary]
masscan = "/usr/bin/masscan"
httpx = "bin/httpx"


[command]
masscan = [
    { key = "binary" },
    { key = "target" },
    { option = "-p", key = "port_range" },
    { option = "--rate", key = "rate" },
    { option = "--source-ip", key = "source_ip" }
]