[api]
version = '0.1.0'
title = 'demo'
description = 'todo'
docs_url = '/'


[dashboard]
url = "/dashboard"


[redis]
host = "redis"
port = 6379


[binary]
masscan = "/usr/bin/masscan"
httpx = "bin/httpx"


[command]
masscan = ["{binary}", "{target}", "-p {port_range}", "--rate {rate}", "--source-ip {source_ip}"]
httpx = ["{binary}", "-p {port}", "{target}"]