[api]
version = '0.1.0'
title = 'demo'
description = 'todo'
docs_url = '/'


[dashboard]
url = "/dashboard"


[redis]
host = "redis"
port = 6379


[actors.masscan]
binary = "/usr/bin/masscan"
command = [
    "{binary}", "{target}",
    ["-p", "{port_range}"],
    ["--rate", "{rate}"],
    ["--source-ip", "{source_ip}"],
    ["-oJ", "-"]
]