[api]
version = '0.1.0'
title = 'demo'
description = 'todo'
docs_url = '/'


[redis]
host = "redis"
port = 6379


[binary]
masscan = "/usr/bin/masscan"
httpx = "bin/httpx"


[command]
masscan = ["{binary}", "-p80", "{target}"]
httpx = ["{binary}", "-p {port}", "{target}"]