[api]
version = '0.1.0'
title = 'demo'
description = 'todo'
docs_url = '/'


[dashboard]
url = "/dashboard"


[redis]
host = "redis"
port = 6379
db = 0


[actors.port_scan.masscan]
binary = "/usr/bin/masscan"
command = [
    { field = "binary" },
    { value = "{target}", field = "target" },
    { name = "-p", field = "ports" },
    { name = "--rate", field = "rate" },
    { name = "--source-ip", field = "source_ip" },
    { name = "-oJ", value = "-" }
]

[actors.port_scan.rustscan]
binary = "bin/rustscan"
command = [
    { field = "binary" },
    { name = "-a", field = "addresses" },
    { name = "--ports", field = "ports"},
    { name = "--range", field = "port_range"},
    { value = "--no-config" },
    { value = "-g" },
]


[actors.port_scan.httpx]
binary = 'bin/httpx'
command = [
    { field = "binary" },
    { name = "-u", field = "target" },
    { name = "-p", field = "port_range" },
    { value = "-json" },
    { value = "-silent" }
]